# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 15) do

  create_table "activations", :force => true do |t|
    t.column "ip_address",     :string,   :limit => 30
    t.column "created_at",     :datetime
    t.column "updated_at",     :datetime
    t.column "completed_at",   :datetime
    t.column "reservation_id", :integer
    t.column "user_id",        :integer
  end

  add_index "activations", ["reservation_id"], :name => "reservation_id"
  add_index "activations", ["user_id"], :name => "user_id"

  create_table "assets", :force => true do |t|
    t.column "name",                   :string
    t.column "platform",               :string
    t.column "producer",               :string
    t.column "model",                  :string,  :limit => 64
    t.column "serial_number",          :string,  :limit => 64
    t.column "hourly_cost_in_dollars", :integer
    t.column "active",                 :boolean
    t.column "virtualized",            :boolean
    t.column "registration_key",       :text
    t.column "type",                   :string
    t.column "lab_id",                 :integer
    t.column "operating_system",       :string
  end

  add_index "assets", ["lab_id"], :name => "lab_id"

  create_table "designations", :force => true do |t|
    t.column "primary_contact", :boolean
    t.column "asset_id",        :integer, :null => false
    t.column "user_id",         :integer, :null => false
  end

  add_index "designations", ["asset_id"], :name => "asset_id"
  add_index "designations", ["user_id"], :name => "user_id"

  create_table "grants", :force => true do |t|
    t.column "approver",            :boolean, :default => true
    t.column "administrator",       :boolean, :default => true
    t.column "super_administrator", :boolean, :default => false
    t.column "lab_id",              :integer,                    :null => false
    t.column "user_id",             :integer,                    :null => false
  end

  add_index "grants", ["lab_id"], :name => "lab_id"
  add_index "grants", ["user_id"], :name => "user_id"

  create_table "hardware_dependencies", :force => true do |t|
    t.column "optional",     :boolean
    t.column "exclusive",    :boolean
    t.column "destructive",  :boolean
    t.column "software_id",  :integer
    t.column "equipment_id", :integer
  end

  add_index "hardware_dependencies", ["software_id"], :name => "hardware_dependencies_ibfk_1"
  add_index "hardware_dependencies", ["equipment_id"], :name => "hardware_dependencies_ibfk_2"

  create_table "interfaces", :force => true do |t|
    t.column "name",       :string,  :limit => 32
    t.column "ip_address", :string,  :limit => 32
    t.column "hostname",   :string,  :limit => 32
    t.column "asset_id",   :integer
    t.column "primary",    :boolean
  end

  add_index "interfaces", ["asset_id"], :name => "asset_id"

  create_table "labs", :force => true do |t|
    t.column "name",       :string,  :limit => 32
    t.column "short_name", :string,  :limit => 16
    t.column "location",   :string
    t.column "district",   :integer
    t.column "region",     :integer
    t.column "division",   :string,  :limit => 32
    t.column "firewall",   :string,  :limit => 32
  end

  create_table "plugin_schema_info", :id => false, :force => true do |t|
    t.column "plugin_name", :string
    t.column "version",     :integer
  end

  create_table "reservations", :force => true do |t|
    t.column "name",               :string
    t.column "start_time",         :datetime
    t.column "end_time",           :datetime
    t.column "reason",             :string
    t.column "comment",            :text
    t.column "approved_at",        :datetime
    t.column "user_id",            :integer
    t.column "approval_code",      :string
    t.column "approval_status",    :string,   :limit => 32
    t.column "approvers_comments", :string
    t.column "lab_id",             :integer
    t.column "event",              :string
  end

  add_index "reservations", ["lab_id"], :name => "lab_id"
  add_index "reservations", ["user_id"], :name => "user_id"

  create_table "resevations_members", :id => false, :force => true do |t|
    t.column "reservation_id", :integer, :null => false
    t.column "member_id",      :integer, :null => false
  end

  add_index "resevations_members", ["reservation_id"], :name => "reservation_id"
  add_index "resevations_members", ["member_id"], :name => "member_id"

  create_table "usages", :force => true do |t|
    t.column "destructive",         :boolean
    t.column "exclusive",           :boolean
    t.column "reservation_id",      :integer
    t.column "asset_id",            :integer
    t.column "version_id",          :integer
    t.column "asset_type",          :string,  :limit => 30
    t.column "optional",            :boolean
    t.column "as_prerequisite_for", :integer
  end

  add_index "usages", ["reservation_id"], :name => "reservation_id"
  add_index "usages", ["asset_id"], :name => "asset_id"
  add_index "usages", ["version_id"], :name => "version_id"

  create_table "users", :force => true do |t|
    t.column "first_name",                :string,   :limit => 128
    t.column "last_name",                 :string,   :limit => 128
    t.column "login",                     :string
    t.column "email",                     :string
    t.column "created_at",                :datetime
    t.column "updated_at",                :datetime
    t.column "remember_token",            :string
    t.column "remember_token_expires_at", :datetime
    t.column "organization",              :string,   :limit => 36
    t.column "super_user",                :boolean
  end

  create_table "versions", :force => true do |t|
    t.column "version",                   :string,  :limit => 16
    t.column "asset_id",                  :integer
    t.column "currently_at_this_version", :boolean
  end

  add_index "versions", ["asset_id"], :name => "asset_id"

  add_foreign_key "activations", ["reservation_id"], "reservations", ["id"], :name => "activations_ibfk_1"
  add_foreign_key "activations", ["user_id"], "users", ["id"], :on_delete => :set_null, :name => "activations_ibfk_2"

  add_foreign_key "assets", ["lab_id"], "labs", ["id"], :on_delete => :set_null, :name => "assets_ibfk_1"
  add_foreign_key "assets", ["lab_id"], "labs", ["id"], :on_delete => :set_null, :name => "assets_ibfk_2"
  add_foreign_key "assets", ["lab_id"], "labs", ["id"], :on_delete => :set_null, :name => "assets_ibfk_3"

  add_foreign_key "designations", ["asset_id"], "assets", ["id"], :on_delete => :cascade, :name => "designations_ibfk_1"
  add_foreign_key "designations", ["user_id"], "users", ["id"], :on_delete => :cascade, :name => "designations_ibfk_2"
  add_foreign_key "designations", ["asset_id"], "assets", ["id"], :on_delete => :cascade, :name => "designations_ibfk_3"
  add_foreign_key "designations", ["user_id"], "users", ["id"], :on_delete => :cascade, :name => "designations_ibfk_4"
  add_foreign_key "designations", ["asset_id"], "assets", ["id"], :on_delete => :cascade, :name => "designations_ibfk_5"
  add_foreign_key "designations", ["user_id"], "users", ["id"], :on_delete => :cascade, :name => "designations_ibfk_6"

  add_foreign_key "grants", ["lab_id"], "labs", ["id"], :on_delete => :cascade, :name => "grants_ibfk_1"
  add_foreign_key "grants", ["user_id"], "users", ["id"], :on_delete => :cascade, :name => "grants_ibfk_2"
  add_foreign_key "grants", ["lab_id"], "labs", ["id"], :on_delete => :cascade, :name => "grants_ibfk_3"
  add_foreign_key "grants", ["user_id"], "users", ["id"], :on_delete => :cascade, :name => "grants_ibfk_4"
  add_foreign_key "grants", ["lab_id"], "labs", ["id"], :on_delete => :cascade, :name => "grants_ibfk_5"
  add_foreign_key "grants", ["user_id"], "users", ["id"], :on_delete => :cascade, :name => "grants_ibfk_6"

  add_foreign_key "hardware_dependencies", ["software_id"], "assets", ["id"], :on_delete => :cascade, :name => "hardware_dependencies_ibfk_1"
  add_foreign_key "hardware_dependencies", ["equipment_id"], "assets", ["id"], :on_delete => :set_null, :name => "hardware_dependencies_ibfk_2"

  add_foreign_key "interfaces", ["asset_id"], "assets", ["id"], :on_delete => :cascade, :name => "interfaces_ibfk_1"
  add_foreign_key "interfaces", ["asset_id"], "assets", ["id"], :on_delete => :cascade, :name => "interfaces_ibfk_2"
  add_foreign_key "interfaces", ["asset_id"], "assets", ["id"], :on_delete => :cascade, :name => "interfaces_ibfk_3"

  add_foreign_key "reservations", ["lab_id"], "labs", ["id"], :on_delete => :set_null, :name => "reservations_ibfk_1"
  add_foreign_key "reservations", ["user_id"], "users", ["id"], :on_delete => :set_null, :name => "reservations_ibfk_2"
  add_foreign_key "reservations", ["lab_id"], "labs", ["id"], :on_delete => :set_null, :name => "reservations_ibfk_3"
  add_foreign_key "reservations", ["user_id"], "users", ["id"], :on_delete => :set_null, :name => "reservations_ibfk_4"

  add_foreign_key "resevations_members", ["reservation_id"], "reservations", ["id"], :on_delete => :cascade, :name => "resevations_members_ibfk_1"
  add_foreign_key "resevations_members", ["member_id"], "users", ["id"], :on_delete => :cascade, :name => "resevations_members_ibfk_2"

  add_foreign_key "usages", ["reservation_id"], "reservations", ["id"], :on_delete => :cascade, :name => "usages_ibfk_1"
  add_foreign_key "usages", ["asset_id"], "assets", ["id"], :on_delete => :set_null, :name => "usages_ibfk_2"
  add_foreign_key "usages", ["version_id"], "versions", ["id"], :on_delete => :set_null, :name => "usages_ibfk_3"
  add_foreign_key "usages", ["reservation_id"], "reservations", ["id"], :on_delete => :cascade, :name => "usages_ibfk_4"
  add_foreign_key "usages", ["asset_id"], "assets", ["id"], :on_delete => :set_null, :name => "usages_ibfk_5"
  add_foreign_key "usages", ["version_id"], "versions", ["id"], :on_delete => :set_null, :name => "usages_ibfk_6"

  add_foreign_key "versions", ["asset_id"], "assets", ["id"], :on_delete => :cascade, :name => "versions_ibfk_1"
  add_foreign_key "versions", ["asset_id"], "assets", ["id"], :on_delete => :cascade, :name => "versions_ibfk_2"
  add_foreign_key "versions", ["asset_id"], "assets", ["id"], :on_delete => :cascade, :name => "versions_ibfk_3"

end
